<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__select-dropdown active</name>
   <tag></tag>
   <elementGuidId>d718bade-b7b2-49bf-860c-08625b33c61d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;newTaskModal&quot;)/div[@class=&quot;modal-dialog  modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body p-5&quot;]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-lg-12 col-md-12&quot;]/div[1]/div[@class=&quot;md-form&quot;]/div[@class=&quot;select-wrapper mdb-select initialized&quot;]/input[@class=&quot;select-dropdown active&quot;][count(. | //*[@type = 'text']) = count(//*[@type = 'text'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/main/div/div[1]/div/div/div[2]/div[2]/div[1]/div/div[3]/div/ul/li[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-dropdown active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-activates</name>
      <type>Main</type>
      <value>select-options-b9ab0254-8d8a-4c55-8fb9-3f87b67521bc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>-- Please select --</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newTaskModal&quot;)/div[@class=&quot;modal-dialog  modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body p-5&quot;]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-lg-12 col-md-12&quot;]/div[1]/div[@class=&quot;md-form&quot;]/div[@class=&quot;select-wrapper mdb-select initialized&quot;]/input[@class=&quot;select-dropdown active&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='-- Please select --'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newTaskModal']/div/div/div[2]/div[2]/div/div/div[4]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
